# Streamlit Configuration for Personal Comment Analyzer
# Following Streamlit 2025 documentation: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
# Theme colors matching project design
base = "dark"
primaryColor = "#667eea"
backgroundColor = "#0b1220"
secondaryBackgroundColor = "#0f172a"
textColor = "#e2e8f0"
font = "sans serif"

[server]
# Server configuration
headless = true
port = 8501
enableXsrfProtection = true
maxUploadSize = 50
fileWatcherType = "auto"
runOnSave = false

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"

[global]
# Global settings
developmentMode = false
suppressDeprecationWarnings = true

[logger]
# Logging configuration
level = "info"
