# Streamlit Configuration for Personal Comment Analyzer
# Following Streamlit 2025 documentation: https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
# Glassmorphism-inspired theme for Personal Comment Analyzer
base = "dark"
primaryColor = "#8B5CF6"          # Purple accent for glassmorphism
backgroundColor = "#0F172A"        # Deep slate background  
secondaryBackgroundColor = "#1E293B"  # Lighter slate for cards
textColor = "#F1F5F9"             # Light text for contrast
font = "sans serif"

[server]
# Server configuration
headless = true
port = 8501
enableXsrfProtection = true
maxUploadSize = 50
# Production settings to prevent inotify limit errors
fileWatcherType = "poll"  # Use polling instead of inotify to prevent OSError [Errno 24]
runOnSave = false         # Disable hot reload in production

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"

[global]
# Global settings
developmentMode = false
suppressDeprecationWarnings = true

[logger]
# Logging configuration
level = "info"
