# Personal Comment Analyzer v2.0 - COMPREHENSIVE PRODUCTION CONFIGURATION TEMPLATE
# COMPLETE E2E VARIABLE MAPPING - Based on Full Codebase Analysis
# Copy this entire content to Streamlit Cloud Secrets panel and update API key
#
# ============================================================================
# 🔑 CRITICAL: API CONFIGURATION (REQUIRED FOR PRODUCTION)
# ============================================================================

# OpenAI API Configuration (MANDATORY - Replace with your API key)
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"  # Replace with sk-...
API_PROVIDER = "openai"                 # "openai" or "azure"
API_TIER = "tier_1"                     # tier_1, tier_2, tier_3, tier_4, tier_5

# LLM Model Configuration
MODEL_NAME = "gpt-4o-mini"              # Model for analysis
MAX_TOKENS_PER_CALL = "12000"           # Max tokens per API call
MAX_TOKENS_PER_REQUEST = "12000"        # Max tokens per request (alias)

# ============================================================================
# 📊 PROCESSING CONFIGURATION (Performance Critical)
# ============================================================================

# Batch Processing Settings
MAX_BATCH_SIZE = "30"                   # Max comments per batch (optimized for stability)
MAX_WORKERS = "1"                       # Streamlit-safe: Sequential processing only
AVG_TOKENS_PER_COMMENT = "150"          # Average tokens per comment estimation
PROMPT_TOKENS = "800"                   # System prompt tokens

# Token Management
MAX_COMMENT_LENGTH = "2000"             # Max characters per comment
MIN_COMMENT_LENGTH = "5"                # Min characters per comment

# ============================================================================
# ⚡ RATE LIMITING & PERFORMANCE (SLA Critical)
# ============================================================================

# Rate Limits (Based on API_TIER)
REQUESTS_PER_MINUTE = "450"             # API requests per minute (90% of tier_1 limit)
TOKENS_PER_MINUTE = "180000"            # API tokens per minute (90% of tier_1 limit)

# Performance SLA Configuration
PERFORMANCE_SLA_TARGET_SECONDS = "10"   # Target processing time (seconds)
PERFORMANCE_SLA_PERCENTILE = "50"       # Performance percentile tracking

# Retry Configuration
MAX_RETRIES = "3"                       # Max API call retries
RETRY_DELAY_SECONDS = "0.5"             # Base retry delay
MAX_RETRIES_NETWORK = "3"               # Network retry attempts
REQUEST_TIMEOUT = "30"                  # HTTP request timeout (seconds)
CONNECTION_TIMEOUT = "10"               # Connection timeout (seconds)

# ============================================================================
# 🎛️ BACKGROUND PROCESSING & THREADING
# ============================================================================

# Background Processing Configuration
ENABLE_BACKGROUND_PROCESSING = "true"   # Background task processing
BACKGROUND_TASK_TIMEOUT = "600"         # Background task timeout (seconds - 10 minutes)
THREAD_POOL_MAX_WORKERS = "1"           # Streamlit-safe: Sequential only
ENABLE_ASYNCIO = "false"                # Disabled for Streamlit compatibility
FORCE_SEQUENTIAL_PROCESSING = "true"    # Force sequential for stability

# ============================================================================
# 🔒 DATA PROCESSING & VALIDATION
# ============================================================================

# File Processing Limits
MAX_FILE_SIZE_MB = "50"                 # Maximum upload file size (MB)
SUPPORTED_FILE_TYPES = ".xlsx,.xls,.csv"  # Supported file extensions
MAX_ROWS_PER_FILE = "50000"             # Max rows per upload
MIN_ROWS_PER_FILE = "1"                 # Min rows per upload

# Data Validation Settings
VALIDATE_INPUT = "true"                 # Validate input data
SANITIZE_OUTPUTS = "true"               # Sanitize output data
ENABLE_FILE_TYPE_VALIDATION = "true"    # Validate file types

# Data Quality Thresholds
MAX_MISSING_PERCENTAGE_COMMENTS = "10"   # Max % missing comments
MAX_MISSING_PERCENTAGE_NPS = "50"        # Max % missing NPS
MAX_MISSING_PERCENTAGE_RATINGS = "30"    # Max % missing ratings

# ============================================================================
# 🌍 LANGUAGE & LOCALIZATION
# ============================================================================

# Language Support
SUPPORTED_LANGS = "es,gn,en"            # Supported languages (Spanish, Guaraní, English)
DEFAULT_LANG = "es"                     # Default language
EMOTION_SYSTEM_VERSION = "1.0"          # Emotion system version

# ============================================================================
# 📊 NPS INFERENCE CONFIGURATION (Post-AI Processing)
# ============================================================================

# NPS Inference Engine Settings
ENABLE_NPS_INFERENCE = "true"           # Post-AI NPS inference from emotions
NPS_INFERENCE_CONFIDENCE_THRESHOLD = "0.5"  # Minimum confidence for inference
NPS_INFERENCE_METHOD = "emotion_weighted"    # Inference algorithm method

# Emotion Weights for NPS Calculation (Expert Tuning)
EMOTION_WEIGHT_ENTUSIASMO = "2.8"       # Strongest positive indicator
EMOTION_WEIGHT_ENOJO = "-3.0"           # Strongest negative indicator
EMOTION_WEIGHT_GRATITUD = "2.5"         # Strong loyalty signal
EMOTION_WEIGHT_FRUSTRACION = "-2.7"     # High dissatisfaction

# ============================================================================
# 📈 ENHANCED DATA PROCESSING (Smart Parsing)
# ============================================================================

# Smart NPS Parser Settings
ENABLE_SMART_NPS_PARSING = "true"       # Enhanced text-to-NPS conversion
ENABLE_SCALE_CONVERSION = "true"        # Convert "/5", "/10", "%" scales
ENABLE_SENTIMENT_NPS_MAPPING = "true"   # Infer NPS from text sentiment

# Response Parser Configuration
ENABLE_JSON_REPAIR = "true"             # Automatic JSON repair for malformed responses
ENABLE_RESPONSE_NORMALIZATION = "true"  # Normalize all responses to standard format
JSON_EXTRACTION_STRATEGIES = "5"        # Number of extraction strategies to try

# ============================================================================
# 🎨 UI/UX CONFIGURATION (User Experience)
# ============================================================================

# Streamlit UI Settings
STREAMLIT_THEME = "dark"                # UI theme (light, dark)
ENABLE_STREAMLIT_ANALYTICS = "false"    # Streamlit analytics
HIDE_STREAMLIT_STYLE = "true"           # Hide Streamlit branding
PAGE_TITLE = "Personal Comment Analyzer"  # Browser page title
PAGE_ICON = "🎭"                        # Browser page icon
LAYOUT = "wide"                         # Page layout (wide, centered)

# Chart Configuration
ENABLE_ADVANCED_CHARTS = "true"         # Advanced visualizations
CHART_DEFAULT_HEIGHT = "500"            # Default chart height
CHART_COLOR_SCHEME = "glassmorphism"    # Color scheme

# Progress & Feedback
ENABLE_BATCH_PROGRESS = "true"          # Show batch processing progress
SHOW_VALIDATION_DASHBOARD = "true"      # Display validation dashboard
SHOW_PROGRESS_INDICATORS = "true"       # Show progress bars
SHOW_PERFORMANCE_METRICS = "true"       # Display performance metrics

# ============================================================================
# 🔄 CACHING & PERFORMANCE OPTIMIZATION
# ============================================================================

# Cache Settings
ENABLE_CACHE = "true"                   # Enable response caching
CACHE_TTL_SECONDS = "3600"             # Cache time-to-live (1 hour)
CACHE_TYPE = "memory"                   # Cache type (memory, redis, file)

# Streamlit Caching
ENABLE_ST_CACHE_DATA = "true"           # Streamlit @st.cache_data
ENABLE_ST_CACHE_RESOURCE = "true"       # Streamlit @st.cache_resource
AUTO_CLEAR_VALIDATION_DATA = "false"    # Keep validation data between runs

# Memory Management
ENABLE_MEMORY_MONITORING = "true"       # Monitor memory usage
MEMORY_WARNING_THRESHOLD = "80"         # Memory warning at 80%
MEMORY_LIMIT_MB = "1024"               # Memory allocation (MB)
ENABLE_GARBAGE_COLLECTION = "true"      # Force garbage collection

# ============================================================================
# 📊 MONITORING & ALERTING (Production Critical)
# ============================================================================

# Usage Monitoring
ENABLE_USAGE_MONITORING = "true"        # Real-time usage tracking
USAGE_WARNING_THRESHOLD = "70"          # Warning at 70% of limits
USAGE_CRITICAL_THRESHOLD = "85"         # Critical at 85% of limits

# Performance Monitoring
ENABLE_PERFORMANCE_MONITORING = "true"  # Track processing performance
LOG_PERFORMANCE_METRICS = "true"        # Log detailed metrics
ENABLE_RATE_LIMIT_MONITORING = "true"   # Intelligent rate limiting
ENABLE_DYNAMIC_BATCH_SIZING = "true"    # Dynamic batch adjustment
ENABLE_TOKEN_USAGE_LOGGING = "true"     # Log token consumption

# Cost Monitoring
ENABLE_COST_MONITORING = "true"         # Track API costs
MAX_DAILY_COST = "100.0"                # Daily cost limit (USD)
ENABLE_USAGE_ALERTS = "true"            # Usage alert notifications

# ============================================================================
# 📝 LOGGING CONFIGURATION (Debug & Production)
# ============================================================================

# Logging Levels
LOG_LEVEL = "INFO"                      # Logging verbosity (DEBUG, INFO, WARNING, ERROR)
ENABLE_DEBUG_LOGGING = "false"          # Enable debug logs
ENABLE_DEBUG_MODE = "false"             # Debug mode

# Logging Features
LOG_TO_FILE = "true"                    # Log to file
LOG_TO_CONSOLE = "true"                 # Log to console
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log format

# Pipeline Logging
ENABLE_PIPELINE_LOGGING = "true"        # External validation logging
ENABLE_STREAMLIT_NATIVE_LOGGING = "true"  # Native Streamlit validation

# ============================================================================
# 🎭 STREAMLIT-NATIVE UX FEATURES
# ============================================================================

# Native Streamlit Components
ENABLE_STATUS_CONTAINERS = "true"       # st.status containers for progress
ENABLE_TOAST_NOTIFICATIONS = "true"     # st.toast for real-time feedback
ENABLE_SUCCESS_CELEBRATIONS = "true"    # st.balloons for completions
ENABLE_SESSION_STATE_TRACKING = "true"  # st.session_state for persistence

# ============================================================================
# 🚀 FEATURE FLAGS (Component Control)
# ============================================================================

# Core Analysis Features
ENABLE_EMOTION_ANALYSIS = "true"        # 16 emotions analysis
ENABLE_NPS_ANALYSIS = "true"            # NPS categorization
ENABLE_CHURN_ANALYSIS = "true"          # Churn risk analysis
ENABLE_PAIN_POINTS_ANALYSIS = "true"    # Pain points detection

# Export Features
ENABLE_EXPORT = "true"                  # File export functionality
ENABLE_EXCEL_EXPORT = "true"            # Excel export
ENABLE_CSV_EXPORT = "true"              # CSV export
ENABLE_JSON_EXPORT = "true"             # JSON export

# Advanced Features
ENABLE_PERFORMANCE_TESTING = "false"    # Performance test endpoints
ENABLE_HOT_RELOAD = "false"             # Hot reload (development)
ENABLE_PROFILING = "false"              # Performance profiling

# ============================================================================
# 🔐 SECURITY & PRIVACY (Enterprise Ready)
# ============================================================================

# Data Security
ENABLE_DATA_ENCRYPTION = "false"        # Encrypt sensitive data
ENABLE_SECURE_HEADERS = "true"          # Security headers
ENABLE_CSRF_PROTECTION = "false"        # CSRF protection

# Privacy Settings
ANONYMIZE_DATA = "false"                # Anonymize processed data
RETENTION_DAYS = "30"                   # Data retention period
ENABLE_GDPR_COMPLIANCE = "false"        # GDPR compliance features

# Audit & Compliance
ENABLE_AUDIT_LOGGING = "false"          # Audit logging (enterprise)
ENABLE_IP_RATE_LIMITING = "false"       # IP-based rate limiting
ENABLE_SECURITY_SCANNING = "false"      # Security scanning

# ============================================================================
# 🌐 DEPLOYMENT & ENVIRONMENT (System Configuration)
# ============================================================================

# Environment Configuration
ENVIRONMENT = "production"              # "development", "staging", "production"
DEPLOYMENT_TIMESTAMP = "2025-09-14"     # Deployment timestamp
APP_VERSION = "2.0.0"                  # Application version

# Resource Limits (Streamlit Cloud)
MAX_CONCURRENT_USERS = "50"            # Expected concurrent users
CPU_LIMIT = "1.0"                      # CPU allocation (cores)

# ============================================================================
# 🧪 TESTING & DEVELOPMENT (Optional)
# ============================================================================

# Development Mode
DEBUG_MODE = "false"                    # Development debug mode
ENABLE_UNIT_TESTS = "false"             # Unit testing endpoints
ENABLE_INTEGRATION_TESTS = "false"      # Integration testing
TEST_DATA_PATH = ""                     # Test data directory

# Mock Configuration (Development Only)
MOCK_FALLBACK_ENABLED = "false"         # Enable mock fallback (ELIMINATED in v2.0)
MOCK_RESPONSE_DELAY = "1.0"             # Mock response delay (seconds)
MOCK_ERROR_RATE = "0.0"                 # Mock error rate (0.0-1.0)

# ============================================================================
# 🔗 EXTERNAL INTEGRATIONS (Future Extensions)
# ============================================================================

# Database (Future)
DATABASE_URL = ""                       # Database connection string
ENABLE_DATABASE_LOGGING = "false"       # Log to database

# External APIs (Future)
WEBHOOK_URL = ""                        # Webhook endpoint
SLACK_WEBHOOK_URL = ""                  # Slack notifications
EMAIL_NOTIFICATIONS = "false"           # Email notifications

# Analytics (Future)
GOOGLE_ANALYTICS_ID = ""                # GA tracking ID
ENABLE_ANALYTICS = "false"              # Analytics tracking

# APM (Future)
ENABLE_APM = "false"                    # Application Performance Monitoring
APM_SERVICE_NAME = "comment-analyzer"   # APM service name

# ============================================================================
# 📋 PRODUCTION DEPLOYMENT CHECKLIST v2.0 (COMPREHENSIVE)
# ============================================================================
#
# 🚨 CRITICAL VARIABLES (MANDATORY):
# - OPENAI_API_KEY: Replace "YOUR_OPENAI_API_KEY_HERE" with your sk-... key
# - API_TIER: Set to match your OpenAI account tier
# - MAX_BATCH_SIZE: Optimized to "30" for stability
# - MAX_WORKERS: Set to "1" for Streamlit Cloud compatibility
#
# COPY-PASTE DEPLOYMENT STEPS:
# 1. 📋 Copy this ENTIRE template content
# 2. 🔑 Replace YOUR_OPENAI_API_KEY_HERE with your real API key
# 3. 📊 Verify API_TIER matches your OpenAI account
# 4. 🌐 Go to Streamlit Cloud app dashboard
# 5. ⚙️ Click "Settings" → "Secrets"
# 6. 📝 Paste ENTIRE content in secrets panel
# 7. 🚀 Deploy and monitor performance
#
# VALIDATION AFTER DEPLOYMENT:
# ✅ Watch for st.toast notifications during processing
# ✅ Check st.status containers for detailed progress
# ✅ Verify charts display with real data
# ✅ Test export functionality (Excel/CSV/JSON)
# ✅ Confirm NPS inference working for missing values
# ✅ Monitor performance metrics in logs
#
# PERFORMANCE TARGETS:
# - ≤10 seconds for 800-1200 comments
# - Sequential processing for Streamlit Cloud stability
# - Rate limiting respects tier limits
# - Memory usage <1GB
# - 99% uptime
#
# System uses COMPREHENSIVE configuration management:
# - 85+ configuration variables
# - Hierarchical fallback: secrets → env → defaults
# - Category-based organization
# - Production-ready security settings
# - Full monitoring and alerting
#
# Total Configuration Variables: 85+
# Critical Variables: 12
# Optional Variables: 73+
# Feature Flags: 20+
# Security Settings: 10+
#
# ============================================================================
# END OF CONFIGURATION TEMPLATE - READY FOR PRODUCTION DEPLOYMENT
# ============================================================================